const providers = {
  a: [
    { name: "Abbott Xena", role: "Dermatologist" },
    { name: "Abbott Kai", role: "Nurse" },
    { name: "Abbott Xena", role: "Nurse" },
    { name: "Abbott Will", role: "Oncologist" },
    { name: "Abbott Uma", role: "Cardiologist" },
    { name: "Abbott Grace", role: "Cardiologist" },
    { name: "Abbott Drew", role: "Psychiatrist" },
    { name: "Abbott Uma", role: "Psychiatrist" },
    { name: "Abbott Grace", role: "Nurse" },
    { name: "Abbott Kai", role: "Physician" }
  ],
  b: [
    { name: "Baker Will", role: "Physical Therapist" },
    { name: "Baker Mia", role: "Radiologist" },
    { name: "Baker Kai", role: "Radiologist" },
    { name: "Baker Toby", role: "Physical Therapist" },
    { name: "Baker Drew", role: "Radiologist" },
    { name: "Baker Harper", role: "Nurse" },
    { name: "Baker Casey", role: "Radiologist" },
    { name: "Baker Kai", role: "Radiologist" },
    { name: "Baker Toby", role: "Physician" },
    { name: "Baker Xena", role: "Physical Therapist" }
  ],
  c: [
    { name: "Carter Will", role: "Radiologist" },
    { name: "Carter Owen", role: "Nurse" },
    { name: "Carter Jack", role: "Dermatologist" },
    { name: "Carter Toby", role: "Oncologist" },
    { name: "Carter Noah", role: "Surgeon" },
    { name: "Carter Jack", role: "Cardiologist" },
    { name: "Carter Alex", role: "Dermatologist" },
    { name: "Carter Drew", role: "Physician" },
    { name: "Carter Jack", role: "Surgeon" },
    { name: "Carter Jack", role: "Physician" }
  ],
  d: [
    { name: "Dawson Grace", role: "Physician" },
    { name: "Dawson Peyton", role: "Physician" },
    { name: "Dawson Quinn", role: "Psychiatrist" },
    { name: "Dawson Ivy", role: "Psychiatrist" },
    { name: "Dawson Ivy", role: "Radiologist" },
    { name: "Dawson Finn", role: "Dermatologist" },
    { name: "Dawson Owen", role: "Nurse" },
    { name: "Dawson Harper", role: "Oncologist" },
    { name: "Dawson Jack", role: "Oncologist" },
    { name: "Dawson Finn", role: "Physician" }
  ],
  e: [
    { name: "Ellis Alex", role: "Physician" },
    { name: "Ellis Peyton", role: "Psychiatrist" },
    { name: "Ellis Evan", role: "Cardiologist" },
    { name: "Ellis Mia", role: "Physician" },
    { name: "Ellis Mia", role: "Surgeon" },
    { name: "Ellis Jack", role: "Pediatrician" },
    { name: "Ellis Peyton", role: "Psychiatrist" },
    { name: "Ellis Noah", role: "Oncologist" },
    { name: "Ellis Evan", role: "Physical Therapist" },
    { name: "Ellis Drew", role: "Physical Therapist" }
  ],
  f: [
    { name: "Foster Alex", role: "Oncologist" },
    { name: "Foster Noah", role: "Physical Therapist" },
    { name: "Foster Sage", role: "Surgeon" },
    { name: "Foster Toby", role: "Surgeon" },
    { name: "Foster Jack", role: "Physical Therapist" },
    { name: "Foster Quinn", role: "Cardiologist" },
    { name: "Foster Vera", role: "Surgeon" },
    { name: "Foster Alex", role: "Psychiatrist" },
    { name: "Foster Peyton", role: "Physician" },
    { name: "Foster Evan", role: "Pediatrician" }
  ],
  g: [
    { name: "Garcia Uma", role: "Cardiologist" },
    { name: "Garcia Ivy", role: "Dermatologist" },
    { name: "Garcia Zane", role: "Physical Therapist" },
    { name: "Garcia Blake", role: "Surgeon" },
    { name: "Garcia Toby", role: "Radiologist" },
    { name: "Garcia Noah", role: "Psychiatrist" },
    { name: "Garcia Yara", role: "Psychiatrist" },
    { name: "Garcia Peyton", role: "Nurse" },
    { name: "Garcia Quinn", role: "Psychiatrist" },
    { name: "Garcia Liam", role: "Surgeon" }
  ],
  h: [
    { name: "Hayes Grace", role: "Surgeon" },
    { name: "Hayes Yara", role: "Physician" },
    { name: "Hayes Yara", role: "Oncologist" },
    { name: "Hayes Xena", role: "Physician" },
    { name: "Hayes Blake", role: "Radiologist" },
    { name: "Hayes Finn", role: "Physician" },
    { name: "Hayes Peyton", role: "Radiologist" },
    { name: "Hayes Uma", role: "Oncologist" },
    { name: "Hayes Yara", role: "Physical Therapist" },
    { name: "Hayes Peyton", role: "Radiologist" }
  ],
  i: [
    { name: "Irwin Vera", role: "Pediatrician" },
    { name: "Irwin Riley", role: "Physician" },
    { name: "Irwin Riley", role: "Nurse" },
    { name: "Irwin Blake", role: "Cardiologist" },
    { name: "Irwin Liam", role: "Surgeon" },
    { name: "Irwin Sage", role: "Oncologist" },
    { name: "Irwin Evan", role: "Radiologist" },
    { name: "Irwin Finn", role: "Surgeon" },
    { name: "Irwin Owen", role: "Dermatologist" },
    { name: "Irwin Toby", role: "Physician" }
  ],
  j: [
    { name: "Jones Grace", role: "Psychiatrist" },
    { name: "Jones Drew", role: "Physician" },
    { name: "Jones Alex", role: "Oncologist" },
    { name: "Jones Riley", role: "Pediatrician" },
    { name: "Jones Toby", role: "Pediatrician" },
    { name: "Jones Vera", role: "Psychiatrist" },
    { name: "Jones Owen", role: "Radiologist" },
    { name: "Jones Zane", role: "Radiologist" },
    { name: "Jones Mia", role: "Psychiatrist" },
    { name: "Jones Riley", role: "Oncologist" }
  ],
  k: [
    { name: "Knight Sage", role: "Pediatrician" },
    { name: "Knight Alex", role: "Radiologist" },
    { name: "Knight Grace", role: "Psychiatrist" },
    { name: "Knight Casey", role: "Cardiologist" },
    { name: "Knight Ivy", role: "Dermatologist" },
    { name: "Knight Uma", role: "Pediatrician" },
    { name: "Knight Zane", role: "Dermatologist" },
    { name: "Knight Grace", role: "Oncologist" },
    { name: "Knight Riley", role: "Physician" },
    { name: "Knight Noah", role: "Nurse" }
  ],
  l: [
    { name: "Lewis Kai", role: "Psychiatrist" },
    { name: "Lewis Liam", role: "Cardiologist" },
    { name: "Lewis Mia", role: "Oncologist" },
    { name: "Lewis Drew", role: "Physician" },
    { name: "Lewis Jack", role: "Surgeon" },
    { name: "Lewis Harper", role: "Psychiatrist" },
    { name: "Lewis Will", role: "Nurse" },
    { name: "Lewis Zane", role: "Dermatologist" },
    { name: "Lewis Mia", role: "Physical Therapist" },
    { name: "Lewis Vera", role: "Physical Therapist" }
  ],
  m: [
    { name: "Miller Peyton", role: "Pediatrician" },
    { name: "Miller Riley", role: "Surgeon" },
    { name: "Miller Toby", role: "Physical Therapist" },
    { name: "Miller Yara", role: "Nurse" },
    { name: "Miller Quinn", role: "Psychiatrist" },
    { name: "Miller Jack", role: "Pediatrician" },
    { name: "Miller Blake", role: "Cardiologist" },
    { name: "Miller Toby", role: "Physician" },
    { name: "Miller Will", role: "Radiologist" },
    { name: "Miller Owen", role: "Nurse" }
  ],
  n: [
    { name: "Nelson Harper", role: "Nurse" },
    { name: "Nelson Zane", role: "Physical Therapist" },
    { name: "Nelson Kai", role: "Pediatrician" },
    { name: "Nelson Riley", role: "Surgeon" },
    { name: "Nelson Liam", role: "Pediatrician" },
    { name: "Nelson Xena", role: "Pediatrician" },
    { name: "Nelson Xena", role: "Pediatrician" },
    { name: "Nelson Ivy", role: "Oncologist" },
    { name: "Nelson Finn", role: "Physical Therapist" },
    { name: "Nelson Liam", role: "Dermatologist" }
  ],
  o: [
    { name: "Owens Toby", role: "Oncologist" },
    { name: "Owens Will", role: "Psychiatrist" },
    { name: "Owens Sage", role: "Dermatologist" },
    { name: "Owens Mia", role: "Dermatologist" },
    { name: "Owens Evan", role: "Radiologist" },
    { name: "Owens Harper", role: "Radiologist" },
    { name: "Owens Kai", role: "Nurse" },
    { name: "Owens Zane", role: "Nurse" },
    { name: "Owens Kai", role: "Physical Therapist" },
    { name: "Owens Riley", role: "Radiologist" }
  ],
  p: [
    { name: "Parker Finn", role: "Physician" },
    { name: "Parker Jack", role: "Cardiologist" },
    { name: "Parker Liam", role: "Pediatrician" },
    { name: "Parker Riley", role: "Dermatologist" },
    { name: "Parker Jack", role: "Surgeon" },
    { name: "Parker Alex", role: "Surgeon" },
    { name: "Parker Liam", role: "Physician" },
    { name: "Parker Uma", role: "Psychiatrist" },
    { name: "Parker Quinn", role: "Dermatologist" },
    { name: "Parker Zane", role: "Surgeon" }
  ],
  q: [
    { name: "Quincy Riley", role: "Physical Therapist" },
    { name: "Quincy Xena", role: "Cardiologist" },
    { name: "Quincy Toby", role: "Oncologist" },
    { name: "Quincy Xena", role: "Physician" },
    { name: "Quincy Riley", role: "Psychiatrist" },
    { name: "Quincy Drew", role: "Radiologist" },
    { name: "Quincy Noah", role: "Surgeon" },
    { name: "Quincy Casey", role: "Cardiologist" },
    { name: "Quincy Finn", role: "Surgeon" },
    { name: "Quincy Zane", role: "Physical Therapist" }
  ],
  r: [
    { name: "Reed Vera", role: "Nurse" },
    { name: "Reed Zane", role: "Psychiatrist" },
    { name: "Reed Xena", role: "Surgeon" },
    { name: "Reed Kai", role: "Surgeon" },
    { name: "Reed Zane", role: "Physical Therapist" },
    { name: "Reed Peyton", role: "Nurse" },
    { name: "Reed Harper", role: "Oncologist" },
    { name: "Reed Zane", role: "Radiologist" },
    { name: "Reed Yara", role: "Oncologist" },
    { name: "Reed Riley", role: "Nurse" }
  ],
  s: [
    { name: "Shaw Quinn", role: "Psychiatrist" },
    { name: "Shaw Noah", role: "Surgeon" },
    { name: "Shaw Finn", role: "Surgeon" },
    { name: "Shaw Xena", role: "Cardiologist" },
    { name: "Shaw Xena", role: "Nurse" },
    { name: "Shaw Zane", role: "Pediatrician" },
    { name: "Shaw Mia", role: "Pediatrician" },
    { name: "Shaw Harper", role: "Physician" },
    { name: "Shaw Finn", role: "Psychiatrist" },
    { name: "Shaw Zane", role: "Radiologist" }
  ],
  t: [
    { name: "Turner Xena", role: "Physician" },
    { name: "Turner Zane", role: "Psychiatrist" },
    { name: "Turner Grace", role: "Dermatologist" },
    { name: "Turner Yara", role: "Radiologist" },
    { name: "Turner Quinn", role: "Physical Therapist" },
    { name: "Turner Harper", role: "Oncologist" },
    { name: "Turner Will", role: "Psychiatrist" },
    { name: "Turner Peyton", role: "Radiologist" },
    { name: "Turner Alex", role: "Psychiatrist" },
    { name: "Turner Liam", role: "Surgeon" }
  ],
  u: [
    { name: "Underwood Toby", role: "Psychiatrist" },
    { name: "Underwood Riley", role: "Dermatologist" },
    { name: "Underwood Casey", role: "Surgeon" },
    { name: "Underwood Toby", role: "Oncologist" },
    { name: "Underwood Sage", role: "Psychiatrist" },
    { name: "Underwood Zane", role: "Surgeon" },
    { name: "Underwood Peyton", role: "Oncologist" },
    { name: "Underwood Quinn", role: "Dermatologist" },
    { name: "Underwood Harper", role: "Pediatrician" },
    { name: "Underwood Evan", role: "Dermatologist" }
  ],
  v: [
    { name: "Vaughn Sage", role: "Psychiatrist" },
    { name: "Vaughn Grace", role: "Oncologist" },
    { name: "Vaughn Noah", role: "Dermatologist" },
    { name: "Vaughn Zane", role: "Dermatologist" },
    { name: "Vaughn Mia", role: "Dermatologist" },
    { name: "Vaughn Riley", role: "Pediatrician" },
    { name: "Vaughn Toby", role: "Cardiologist" },
    { name: "Vaughn Zane", role: "Physician" },
    { name: "Vaughn Will", role: "Cardiologist" },
    { name: "Vaughn Mia", role: "Nurse" }
  ],
  w: [
    { name: "White Grace", role: "Surgeon" },
    { name: "White Harper", role: "Nurse" },
    { name: "White Sage", role: "Surgeon" },
    { name: "White Uma", role: "Pediatrician" },
    { name: "White Toby", role: "Physical Therapist" },
    { name: "White Casey", role: "Physical Therapist" },
    { name: "White Vera", role: "Psychiatrist" },
    { name: "White Harper", role: "Radiologist" },
    { name: "White Quinn", role: "Dermatologist" },
    { name: "White Grace", role: "Cardiologist" }
  ],
  x: [
    { name: "Xavier Jack", role: "Physician" },
    { name: "Xavier Liam", role: "Surgeon" },
    { name: "Xavier Owen", role: "Physician" },
    { name: "Xavier Vera", role: "Nurse" },
    { name: "Xavier Blake", role: "Radiologist" },
    { name: "Xavier Harper", role: "Radiologist" },
    { name: "Xavier Finn", role: "Psychiatrist" },
    { name: "Xavier Yara", role: "Radiologist" },
    { name: "Xavier Harper", role: "Cardiologist" },
    { name: "Xavier Vera", role: "Oncologist" }
  ],
  y: [
    { name: "Young Casey", role: "Dermatologist" },
    { name: "Young Harper", role: "Surgeon" },
    { name: "Young Evan", role: "Surgeon" },
    { name: "Young Alex", role: "Oncologist" },
    { name: "Young Uma", role: "Psychiatrist" },
    { name: "Young Will", role: "Physical Therapist" },
    { name: "Young Owen", role: "Surgeon" },
    { name: "Young Owen", role: "Pediatrician" },
    { name: "Young Liam", role: "Physician" },
    { name: "Young Toby", role: "Nurse" }
  ],
  z: [
    { name: "Zimmer Casey", role: "Nurse" },
    { name: "Zimmer Noah", role: "Surgeon" },
    { name: "Zimmer Yara", role: "Oncologist" },
    { name: "Zimmer Kai", role: "Radiologist" },
    { name: "Zimmer Sage", role: "Psychiatrist" },
    { name: "Zimmer Noah", role: "Cardiologist" },
    { name: "Zimmer Xena", role: "Radiologist" },
    { name: "Zimmer Toby", role: "Physical Therapist" },
    { name: "Zimmer Jack", role: "Surgeon" },
    { name: "Zimmer Alex", role: "Cardiologist" }
  ]
};

export { providers };
