import { geistMono, geistSans } from "@/assets/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "../assets/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `antialiased`,
          geistSans.variable,
          geistMono.variable,
          geistSans.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
